server:
  port: ${PORT:8082}

spring:
  application:
    name: 29cm-homework

  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:homework
      username: sa
      password:

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
      format_sql: true
      use_sql_comments: true
      type: info
    open-in-view: false

logging:
  level:
    root: info
    kr.co.cm29.homework: debug
    org:
      hibernate:
        SQL: info
        type: info
  file:
    name: logs/29cm-homework.log